mod capabilities;
mod common;
mod lifecycle;
mod pairings;
mod providers;
mod router;
mod status;

pub(crate) mod connectors {
    pub(crate) mod discord;
}

use anyhow::{Context, Result};
use std::io::Write;

use crate::{args::ChannelsCommand, output};

use common::{
    load_channel_credential, normalize_generic_account_id, normalize_string_list,
    post_discord_account_action, provider_label, resolve_entity_label, unsupported_provider_action,
};
pub(crate) use common::{post_connector_action, resolve_connector_status};
use lifecycle::emit_channel_lifecycle_disable;

pub(crate) fn run(command: ChannelsCommand) -> Result<()> {
    match command {
        ChannelsCommand::Add {
            provider,
            account_id,
            interactive,
            credential,
            credential_stdin,
            credential_prompt,
            mode,
            inbound_scope,
            allow_from,
            deny_from,
            require_mention,
            mention_patterns,
            concurrency_limit,
            direct_message_policy,
            broadcast_strategy,
            confirm_open_guild_channels,
            verify_channel_id,
            url,
            token,
            principal,
            device_id,
            channel,
            json,
        } => lifecycle::run_channel_lifecycle_upsert(
            "add",
            provider,
            account_id,
            interactive,
            credential,
            credential_stdin,
            credential_prompt,
            mode,
            inbound_scope,
            allow_from,
            deny_from,
            require_mention,
            mention_patterns,
            concurrency_limit,
            direct_message_policy,
            broadcast_strategy,
            confirm_open_guild_channels,
            verify_channel_id,
            url,
            token,
            principal,
            device_id,
            channel,
            output::preferred_json(json),
        )?,
        ChannelsCommand::Login {
            provider,
            account_id,
            credential,
            credential_stdin,
            credential_prompt,
            mode,
            inbound_scope,
            allow_from,
            deny_from,
            require_mention,
            mention_patterns,
            concurrency_limit,
            direct_message_policy,
            broadcast_strategy,
            confirm_open_guild_channels,
            verify_channel_id,
            url,
            token,
            principal,
            device_id,
            channel,
            json,
        } => lifecycle::run_channel_lifecycle_upsert(
            "login",
            provider,
            account_id,
            false,
            credential,
            credential_stdin,
            credential_prompt,
            mode,
            inbound_scope,
            allow_from,
            deny_from,
            require_mention,
            mention_patterns,
            concurrency_limit,
            direct_message_policy,
            broadcast_strategy,
            confirm_open_guild_channels,
            verify_channel_id,
            url,
            token,
            principal,
            device_id,
            channel,
            output::preferred_json(json),
        )?,
        ChannelsCommand::Logout {
            provider,
            account_id,
            keep_credential,
            url,
            token,
            principal,
            device_id,
            channel,
            json,
        } => lifecycle::run_channel_lifecycle_disable(
            "logout",
            provider,
            account_id,
            keep_credential,
            url,
            token,
            principal,
            device_id,
            channel,
            output::preferred_json(json),
        )?,
        ChannelsCommand::Remove {
            provider,
            account_id,
            keep_credential,
            url,
            token,
            principal,
            device_id,
            channel,
            json,
        } => lifecycle::run_channel_lifecycle_disable(
            "remove",
            provider,
            account_id,
            keep_credential,
            url,
            token,
            principal,
            device_id,
            channel,
            output::preferred_json(json),
        )?,
        ChannelsCommand::Capabilities {
            connector_id,
            provider,
            account_id,
            url,
            token,
            principal,
            device_id,
            channel,
            json,
        } => capabilities::run_capabilities(
            connector_id,
            provider,
            account_id,
            url,
            token,
            principal,
            device_id,
            channel,
            output::preferred_json(json),
        )?,
        ChannelsCommand::Resolve { provider, account_id, entity, value, json } => {
            capabilities::run_resolution(
                provider,
                account_id,
                entity,
                value,
                output::preferred_json(json),
            )?;
        }
        ChannelsCommand::Pairings {
            connector_id,
            provider,
            account_id,
            url,
            token,
            principal,
            device_id,
            channel,
            json,
        } => pairings::run_pairings(
            connector_id,
            provider,
            account_id,
            url,
            token,
            principal,
            device_id,
            channel,
            output::preferred_json(json),
        )?,
        ChannelsCommand::PairingCode {
            connector_id,
            provider,
            account_id,
            issued_by,
            ttl_ms,
            url,
            token,
            principal,
            device_id,
            channel,
            json,
        } => pairings::run_pairing_code(
            connector_id,
            provider,
            account_id,
            issued_by,
            ttl_ms,
            url,
            token,
            principal,
            device_id,
            channel,
            output::preferred_json(json),
        )?,
        ChannelsCommand::Qr {
            connector_id,
            provider,
            account_id,
            issued_by,
            ttl_ms,
            artifact,
            url,
            token,
            principal,
            device_id,
            channel,
            json,
        } => pairings::run_qr(
            connector_id,
            provider,
            account_id,
            issued_by,
            ttl_ms,
            artifact,
            url,
            token,
            principal,
            device_id,
            channel,
            output::preferred_json(json),
        )?,
        ChannelsCommand::Discord { command } => connectors::discord::run(command)?,
        ChannelsCommand::Router { command } => router::run(command)?,
        ChannelsCommand::List { url, token, principal, device_id, channel, json } => {
            status::run_list(
                url,
                token,
                principal,
                device_id,
                channel,
                output::preferred_json(json),
            )?;
        }
        ChannelsCommand::Status {
            connector_id,
            provider,
            account_id,
            url,
            token,
            principal,
            device_id,
            channel,
            json,
        } => status::run_status(
            connector_id,
            provider,
            account_id,
            url,
            token,
            principal,
            device_id,
            channel,
            output::preferred_json(json),
        )?,
        ChannelsCommand::HealthRefresh {
            connector_id,
            provider,
            account_id,
            verify_channel_id,
            url,
            token,
            principal,
            device_id,
            channel,
            json,
        } => status::run_health_refresh(
            connector_id,
            provider,
            account_id,
            verify_channel_id,
            url,
            token,
            principal,
            device_id,
            channel,
            output::preferred_json(json),
        )?,
        ChannelsCommand::Enable {
            connector_id,
            url,
            token,
            principal,
            device_id,
            channel,
            json,
        } => status::run_enable_toggle(
            connector_id,
            true,
            url,
            token,
            principal,
            device_id,
            channel,
            output::preferred_json(json),
        )?,
        ChannelsCommand::QueuePause {
            connector_id,
            url,
            token,
            principal,
            device_id,
            channel,
            json,
        } => status::run_queue_action(
            connector_id,
            "/operations/queue/pause",
            "failed to call channels queue pause endpoint",
            url,
            token,
            principal,
            device_id,
            channel,
            output::preferred_json(json),
        )?,
        ChannelsCommand::QueueResume {
            connector_id,
            url,
            token,
            principal,
            device_id,
            channel,
            json,
        } => status::run_queue_action(
            connector_id,
            "/operations/queue/resume",
            "failed to call channels queue resume endpoint",
            url,
            token,
            principal,
            device_id,
            channel,
            output::preferred_json(json),
        )?,
        ChannelsCommand::QueueDrain {
            connector_id,
            url,
            token,
            principal,
            device_id,
            channel,
            json,
        } => status::run_queue_action(
            connector_id,
            "/operations/queue/drain",
            "failed to call channels queue drain endpoint",
            url,
            token,
            principal,
            device_id,
            channel,
            output::preferred_json(json),
        )?,
        ChannelsCommand::DeadLetterReplay {
            connector_id,
            dead_letter_id,
            url,
            token,
            principal,
            device_id,
            channel,
            json,
        } => status::run_dead_letter_action(
            connector_id,
            dead_letter_id,
            "replay",
            url,
            token,
            principal,
            device_id,
            channel,
            output::preferred_json(json),
        )?,
        ChannelsCommand::DeadLetterDiscard {
            connector_id,
            dead_letter_id,
            url,
            token,
            principal,
            device_id,
            channel,
            json,
        } => status::run_dead_letter_action(
            connector_id,
            dead_letter_id,
            "discard",
            url,
            token,
            principal,
            device_id,
            channel,
            output::preferred_json(json),
        )?,
        ChannelsCommand::Disable {
            connector_id,
            url,
            token,
            principal,
            device_id,
            channel,
            json,
        } => status::run_enable_toggle(
            connector_id,
            false,
            url,
            token,
            principal,
            device_id,
            channel,
            output::preferred_json(json),
        )?,
        ChannelsCommand::Logs {
            connector_id,
            provider,
            account_id,
            url,
            token,
            principal,
            device_id,
            channel,
            limit,
            json,
        } => status::run_logs(
            connector_id,
            provider,
            account_id,
            url,
            token,
            principal,
            device_id,
            channel,
            limit,
            output::preferred_json(json),
        )?,
        ChannelsCommand::Test {
            connector_id,
            text,
            url,
            token,
            principal,
            device_id,
            channel,
            conversation_id,
            sender_id,
            sender_display,
            simulate_crash_once,
            is_direct_message,
            requested_broadcast,
            json,
        } => status::run_test(
            connector_id,
            text,
            url,
            token,
            principal,
            device_id,
            channel,
            conversation_id,
            sender_id,
            sender_display,
            simulate_crash_once,
            is_direct_message,
            requested_broadcast,
            output::preferred_json(json),
        )?,
    }

    std::io::stdout().flush().context("stdout flush failed")
}
