[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"

function Add-SetEntry {
    param(
        [Parameter(Mandatory = $true)]
        [hashtable]$Map,
        [Parameter(Mandatory = $true)]
        [string]$Key,
        [Parameter(Mandatory = $true)]
        [string]$Value
    )

    if (-not $Map.ContainsKey($Key)) {
        $Map[$Key] = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::Ordinal)
    }
    [void]$Map[$Key].Add($Value)
}

function ConvertTo-RustModule {
    param([Parameter(Mandatory = $true)][string]$PackageName)
    return [System.Text.RegularExpressions.Regex]::Replace($PackageName, "[\.\-]", "_")
}

function ConvertTo-Namespace {
    param([Parameter(Mandatory = $true)][string]$PackageName)

    $builder = [System.Text.StringBuilder]::new()
    foreach ($segment in ($PackageName -split "\.")) {
        $normalized = [System.Text.RegularExpressions.Regex]::Replace($segment, "[^A-Za-z0-9]", " ")
        foreach ($piece in ($normalized -split "\s+")) {
            if ([string]::IsNullOrWhiteSpace($piece)) {
                continue
            }
            $null = $builder.Append(([char]::ToUpperInvariant($piece[0])).ToString())
            if ($piece.Length -gt 1) {
                $null = $builder.Append($piece.Substring(1))
            }
        }
    }
    return $builder.ToString()
}

function ConvertTo-LowerFirst {
    param([Parameter(Mandatory = $true)][string]$InputText)
    if ([string]::IsNullOrEmpty($InputText)) {
        return ""
    }
    if ($InputText.Length -eq 1) {
        return $InputText.ToLowerInvariant()
    }
    return $InputText.Substring(0, 1).ToLowerInvariant() + $InputText.Substring(1)
}

function Get-SortedValues {
    param(
        [Parameter(Mandatory = $true)]
        [hashtable]$Map,
        [Parameter(Mandatory = $true)]
        [string]$Key
    )

    if (-not $Map.ContainsKey($Key)) {
        return @()
    }
    return @($Map[$Key] | Sort-Object)
}

function Write-Utf8NoBomFile {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [string[]]$Lines
    )

    $content = ($Lines -join "`n") + "`n"
    $encoding = [System.Text.UTF8Encoding]::new($false)
    [System.IO.File]::WriteAllText($Path, $content, $encoding)
}

$rootDir = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$protoDir = Join-Path $rootDir "schemas\proto"
$outDir = Join-Path $rootDir "schemas\generated"
$rustOut = Join-Path $outDir "rust\protocol_stubs.rs"
$swiftOut = Join-Path $outDir "swift\ProtocolStubs.swift"
$kotlinOut = Join-Path $outDir "kotlin\ProtocolStubs.kt"

New-Item -ItemType Directory -Path (Join-Path $outDir "rust") -Force | Out-Null
New-Item -ItemType Directory -Path (Join-Path $outDir "swift") -Force | Out-Null
New-Item -ItemType Directory -Path (Join-Path $outDir "kotlin") -Force | Out-Null

$protoFiles = Get-ChildItem -Path $protoDir -Recurse -File -Filter "*.proto" | Sort-Object FullName
if ($protoFiles.Count -eq 0) {
    throw "No .proto files found under $protoDir"
}

$packages = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::Ordinal)
$messagesByPackage = @{}
$servicesByPackage = @{}
$rpcsByPackageService = @{}

foreach ($file in $protoFiles) {
    $lines = Get-Content -Path $file.FullName
    $packageName = $null
    foreach ($line in $lines) {
        if ($line -match "^\s*package\s+([^;]+);") {
            $packageName = $matches[1]
            break
        }
    }

    if ([string]::IsNullOrWhiteSpace($packageName)) {
        throw "Proto file '$($file.FullName)' is missing a package declaration."
    }

    [void]$packages.Add($packageName)

    foreach ($line in $lines) {
        if ($line -match "^\s*message\s+([A-Za-z0-9_]+)\s*\{") {
            Add-SetEntry -Map $messagesByPackage -Key $packageName -Value $matches[1]
        }
        if ($line -match "^\s*service\s+([A-Za-z0-9_]+)\s*\{") {
            Add-SetEntry -Map $servicesByPackage -Key $packageName -Value $matches[1]
        }
    }

    $currentService = ""
    foreach ($line in $lines) {
        if ($line -match "^\s*service\s+([A-Za-z0-9_]+)\s*\{") {
            $currentService = $matches[1]
            continue
        }
        if ($line -match "^\s*\}\s*$") {
            $currentService = ""
            continue
        }
        if ($currentService -and ($line -match "^\s*rpc\s+([A-Za-z0-9_]+)\s*\(")) {
            $rpcKey = "$packageName`t$currentService"
            Add-SetEntry -Map $rpcsByPackageService -Key $rpcKey -Value $matches[1]
        }
    }
}

$sortedPackages = @($packages | Sort-Object)

$rustLines = New-Object System.Collections.Generic.List[string]
$rustLines.Add("// @generated by scripts/protocol/generate-stubs.sh. DO NOT EDIT.")
$rustLines.Add("#![allow(dead_code)]")
$rustLines.Add("#![allow(non_snake_case)]")
$rustLines.Add("")
$rustLines.Add("pub const PROTOCOL_MAJOR_VERSION: u32 = 1;")

foreach ($packageName in $sortedPackages) {
    $rustModule = ConvertTo-RustModule -PackageName $packageName
    $rustLines.Add("")
    $rustLines.Add("pub mod $rustModule {")

    foreach ($messageName in (Get-SortedValues -Map $messagesByPackage -Key $packageName)) {
        $rustLines.Add("    #[derive(Debug, Clone, Default, PartialEq, Eq)]")
        $rustLines.Add("    pub struct $messageName;")
    }

    foreach ($serviceName in (Get-SortedValues -Map $servicesByPackage -Key $packageName)) {
        $rpcKey = "$packageName`t$serviceName"
        $rpcNames = Get-SortedValues -Map $rpcsByPackageService -Key $rpcKey
        $rustLines.Add("    pub trait ${serviceName}Client {")
        if ($rpcNames.Count -eq 0) {
            $rustLines.Add("        fn noop(&self);")
        } else {
            foreach ($rpcName in $rpcNames) {
                $rustLines.Add("        fn ${rpcName}(&self);")
            }
        }
        $rustLines.Add("    }")
    }

    $rustLines.Add("}")
}

$swiftLines = New-Object System.Collections.Generic.List[string]
$swiftLines.Add("// @generated by scripts/protocol/generate-stubs.sh. DO NOT EDIT.")

foreach ($packageName in $sortedPackages) {
    $namespace = ConvertTo-Namespace -PackageName $packageName
    $swiftLines.Add("")
    $swiftLines.Add("public enum $namespace {")

    foreach ($messageName in (Get-SortedValues -Map $messagesByPackage -Key $packageName)) {
        $swiftLines.Add("    public struct ${messageName}: Equatable {")
        $swiftLines.Add("        public init() {}")
        $swiftLines.Add("    }")
    }

    foreach ($serviceName in (Get-SortedValues -Map $servicesByPackage -Key $packageName)) {
        $rpcKey = "$packageName`t$serviceName"
        $rpcNames = Get-SortedValues -Map $rpcsByPackageService -Key $rpcKey
        $swiftLines.Add("    public protocol ${serviceName}Client {")
        if ($rpcNames.Count -eq 0) {
            $swiftLines.Add("        func noop()")
        } else {
            foreach ($rpcName in $rpcNames) {
                $methodName = ConvertTo-LowerFirst -InputText $rpcName
                $swiftLines.Add("        func $methodName()")
            }
        }
        $swiftLines.Add("    }")
    }

    $swiftLines.Add("}")
}

$kotlinLines = New-Object System.Collections.Generic.List[string]
$kotlinLines.Add("// @generated by scripts/protocol/generate-stubs.sh. DO NOT EDIT.")
$kotlinLines.Add("package palyra.generated")

foreach ($packageName in $sortedPackages) {
    $namespace = ConvertTo-Namespace -PackageName $packageName
    $kotlinLines.Add("")
    $kotlinLines.Add("object $namespace {")

    foreach ($messageName in (Get-SortedValues -Map $messagesByPackage -Key $packageName)) {
        $kotlinLines.Add("    data class $messageName(val placeholder: Int = 0)")
    }

    foreach ($serviceName in (Get-SortedValues -Map $servicesByPackage -Key $packageName)) {
        $rpcKey = "$packageName`t$serviceName"
        $rpcNames = Get-SortedValues -Map $rpcsByPackageService -Key $rpcKey
        $kotlinLines.Add("    interface ${serviceName}Client {")
        if ($rpcNames.Count -eq 0) {
            $kotlinLines.Add("        fun noop()")
        } else {
            foreach ($rpcName in $rpcNames) {
                $methodName = ConvertTo-LowerFirst -InputText $rpcName
                $kotlinLines.Add("        fun $methodName()")
            }
        }
        $kotlinLines.Add("    }")
    }

    $kotlinLines.Add("}")
}

Write-Utf8NoBomFile -Path $rustOut -Lines $rustLines
Write-Utf8NoBomFile -Path $swiftOut -Lines $swiftLines
Write-Utf8NoBomFile -Path $kotlinOut -Lines $kotlinLines

Write-Output "Generated protocol stubs:"
Write-Output "  - $rustOut"
Write-Output "  - $swiftOut"
Write-Output "  - $kotlinOut"
