#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
PROTO_DIR="$ROOT_DIR/schemas/proto"
OUT_DIR="$ROOT_DIR/schemas/generated"
RUST_OUT="$OUT_DIR/rust/protocol_stubs.rs"
SWIFT_OUT="$OUT_DIR/swift/ProtocolStubs.swift"
KOTLIN_OUT="$OUT_DIR/kotlin/ProtocolStubs.kt"

mkdir -p "$OUT_DIR/rust" "$OUT_DIR/swift" "$OUT_DIR/kotlin"

tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT

packages_file="$tmp_dir/packages.tsv"
messages_file="$tmp_dir/messages.tsv"
services_file="$tmp_dir/services.tsv"
rpcs_file="$tmp_dir/rpcs.tsv"

: >"$packages_file"
: >"$messages_file"
: >"$services_file"
: >"$rpcs_file"

proto_files=()
while IFS= read -r file; do
  proto_files+=("$file")
done < <(find "$PROTO_DIR" -type f -name '*.proto' | sort)

if [ "${#proto_files[@]}" -eq 0 ]; then
  echo "No .proto files found under $PROTO_DIR" >&2
  exit 1
fi

for file in "${proto_files[@]}"; do
  package_name="$(sed -nE 's/^[[:space:]]*package[[:space:]]+([^;]+);/\1/p' "$file" | head -n 1)"
  if [ -z "$package_name" ]; then
    echo "Proto file '$file' is missing a package declaration." >&2
    exit 1
  fi

  printf "%s\n" "$package_name" >>"$packages_file"

  while IFS= read -r message_name; do
    printf "%s\t%s\n" "$package_name" "$message_name" >>"$messages_file"
  done < <(sed -nE 's/^[[:space:]]*message[[:space:]]+([A-Za-z0-9_]+)[[:space:]]*\{/\1/p' "$file")

  while IFS= read -r service_name; do
    printf "%s\t%s\n" "$package_name" "$service_name" >>"$services_file"
  done < <(sed -nE 's/^[[:space:]]*service[[:space:]]+([A-Za-z0-9_]+)[[:space:]]*\{/\1/p' "$file")

  current_service=""
  while IFS= read -r line; do
    if [[ "$line" =~ ^[[:space:]]*service[[:space:]]+([A-Za-z0-9_]+)[[:space:]]*\{ ]]; then
      current_service="${BASH_REMATCH[1]}"
      continue
    fi
    if [[ "$line" =~ ^[[:space:]]*\}[[:space:]]*$ ]]; then
      current_service=""
      continue
    fi
    if [[ -n "$current_service" && "$line" =~ ^[[:space:]]*rpc[[:space:]]+([A-Za-z0-9_]+)[[:space:]]*\( ]]; then
      printf "%s\t%s\t%s\n" "$package_name" "$current_service" "${BASH_REMATCH[1]}" >>"$rpcs_file"
    fi
  done <"$file"
done

sort -u "$packages_file" -o "$packages_file"
sort -u "$messages_file" -o "$messages_file"
sort -u "$services_file" -o "$services_file"
sort -u "$rpcs_file" -o "$rpcs_file"

package_to_rust_module() {
  printf "%s" "$1" | tr '.-' '__'
}

package_to_namespace() {
  printf "%s" "$1" | awk -F'.' '
    {
      out = "";
      for (i = 1; i <= NF; i++) {
        segment = $i;
        gsub(/[^[:alnum:]]/, " ", segment);
        count = split(segment, pieces, /[[:space:]]+/);
        for (j = 1; j <= count; j++) {
          if (pieces[j] != "") {
            out = out toupper(substr(pieces[j], 1, 1)) substr(pieces[j], 2);
          }
        }
      }
      printf "%s", out;
    }
  '
}

lower_first() {
  input="$1"
  if [ -z "$input" ]; then
    printf ""
    return
  fi
  first="$(printf "%s" "$input" | cut -c1 | tr '[:upper:]' '[:lower:]')"
  rest="$(printf "%s" "$input" | cut -c2-)"
  printf "%s%s" "$first" "$rest"
}

{
  echo "// @generated by scripts/protocol/generate-stubs.sh. DO NOT EDIT."
  echo "#![allow(dead_code)]"
  echo "#![allow(non_snake_case)]"
  echo ""
  echo "pub const PROTOCOL_MAJOR_VERSION: u32 = 1;"

  while IFS= read -r package_name; do
    rust_module="$(package_to_rust_module "$package_name")"
    echo ""
    echo "pub mod $rust_module {"
    while IFS= read -r message_name; do
      echo "    #[derive(Debug, Clone, Default, PartialEq, Eq)]"
      echo "    pub struct $message_name;"
    done < <(awk -F '\t' -v pkg="$package_name" '$1 == pkg { print $2 }' "$messages_file")

    while IFS= read -r service_name; do
      echo "    pub trait ${service_name}Client {"
      has_methods=0
      while IFS= read -r rpc_name; do
        has_methods=1
        echo "        fn ${rpc_name}(&self);"
      done < <(awk -F '\t' -v pkg="$package_name" -v svc="$service_name" '$1 == pkg && $2 == svc { print $3 }' "$rpcs_file")

      if [ "$has_methods" -eq 0 ]; then
        echo "        fn noop(&self);"
      fi
      echo "    }"
    done < <(awk -F '\t' -v pkg="$package_name" '$1 == pkg { print $2 }' "$services_file")

    echo "}"
  done <"$packages_file"
} >"$RUST_OUT"

{
  echo "// @generated by scripts/protocol/generate-stubs.sh. DO NOT EDIT."
  while IFS= read -r package_name; do
    namespace="$(package_to_namespace "$package_name")"
    echo ""
    echo "public enum $namespace {"
    while IFS= read -r message_name; do
      echo "    public struct $message_name: Equatable {"
      echo "        public init() {}"
      echo "    }"
    done < <(awk -F '\t' -v pkg="$package_name" '$1 == pkg { print $2 }' "$messages_file")

    while IFS= read -r service_name; do
      echo "    public protocol ${service_name}Client {"
      has_methods=0
      while IFS= read -r rpc_name; do
        has_methods=1
        rpc_method="$(lower_first "$rpc_name")"
        echo "        func $rpc_method()"
      done < <(awk -F '\t' -v pkg="$package_name" -v svc="$service_name" '$1 == pkg && $2 == svc { print $3 }' "$rpcs_file")

      if [ "$has_methods" -eq 0 ]; then
        echo "        func noop()"
      fi
      echo "    }"
    done < <(awk -F '\t' -v pkg="$package_name" '$1 == pkg { print $2 }' "$services_file")
    echo "}"
  done <"$packages_file"
} >"$SWIFT_OUT"

{
  echo "// @generated by scripts/protocol/generate-stubs.sh. DO NOT EDIT."
  echo "package palyra.generated"
  while IFS= read -r package_name; do
    namespace="$(package_to_namespace "$package_name")"
    echo ""
    echo "object $namespace {"
    while IFS= read -r message_name; do
      echo "    data class $message_name(val placeholder: Int = 0)"
    done < <(awk -F '\t' -v pkg="$package_name" '$1 == pkg { print $2 }' "$messages_file")

    while IFS= read -r service_name; do
      echo "    interface ${service_name}Client {"
      has_methods=0
      while IFS= read -r rpc_name; do
        has_methods=1
        rpc_method="$(lower_first "$rpc_name")"
        echo "        fun $rpc_method()"
      done < <(awk -F '\t' -v pkg="$package_name" -v svc="$service_name" '$1 == pkg && $2 == svc { print $3 }' "$rpcs_file")

      if [ "$has_methods" -eq 0 ]; then
        echo "        fun noop()"
      fi
      echo "    }"
    done < <(awk -F '\t' -v pkg="$package_name" '$1 == pkg { print $2 }' "$services_file")
    echo "}"
  done <"$packages_file"
} >"$KOTLIN_OUT"

echo "Generated protocol stubs:"
echo "  - $RUST_OUT"
echo "  - $SWIFT_OUT"
echo "  - $KOTLIN_OUT"
