use crate::*;

#[allow(clippy::too_many_arguments)]
pub(crate) fn run_configure(
    path: Option<String>,
    sections: Vec<ConfigureSectionArg>,
    non_interactive: bool,
    accept_risk: bool,
    json: bool,
    workspace_root: Option<String>,
    auth_method: Option<OnboardingAuthMethodArg>,
    api_key_env: Option<String>,
    api_key_stdin: bool,
    api_key_prompt: bool,
    bind_profile: Option<GatewayBindProfileArg>,
    daemon_port: Option<u16>,
    grpc_port: Option<u16>,
    quic_port: Option<u16>,
    tls_scaffold: Option<InitTlsScaffoldArg>,
    tls_cert_path: Option<String>,
    tls_key_path: Option<String>,
    remote_base_url: Option<String>,
    admin_token_env: Option<String>,
    admin_token_stdin: bool,
    admin_token_prompt: bool,
    remote_verification: Option<RemoteVerificationModeArg>,
    pinned_server_cert_sha256: Option<String>,
    pinned_gateway_ca_sha256: Option<String>,
    ssh_target: Option<String>,
    skip_health: bool,
    skip_channels: bool,
    skip_skills: bool,
) -> Result<()> {
    commands::operator_wizard::run_configure_wizard(
        commands::operator_wizard::ConfigureWizardRequest {
            path,
            sections,
            non_interactive,
            accept_risk,
            json,
            workspace_root,
            auth_method,
            api_key_env,
            api_key_stdin,
            api_key_prompt,
            bind_profile,
            daemon_port,
            grpc_port,
            quic_port,
            tls_scaffold,
            tls_cert_path,
            tls_key_path,
            remote_base_url,
            admin_token_env,
            admin_token_stdin,
            admin_token_prompt,
            remote_verification,
            pinned_server_cert_sha256,
            pinned_gateway_ca_sha256,
            ssh_target,
            skip_health,
            skip_channels,
            skip_skills,
        },
    )
}
