included:
  - .

excluded:
  - .build
  - DerivedData

opt_in_rules:
  - empty_count
  - explicit_init
  - first_where
  - force_unwrapping
  - multiline_parameters

disabled_rules:
  - trailing_whitespace

line_length:
  warning: 120
  error: 160

identifier_name:
  min_length: 2
  max_length: 40
