//! Orphaned pre-modularization OAuth module — NOT part of the crate.
//!
//! AIDEV-NOTE: this file is not declared in `lib.rs` (no `mod oauth;`), so it is never
//! compiled. It is a leftover from commit e37a3ff0, which split its contents into
//! `refresh.rs` and `models.rs`; it would not even build today (it imports items from
//! `crate::models` that live elsewhere). Do not edit this file as if it were live code.
//! Delete it in a dedicated change once confirmed nothing references it.

use std::time::Duration;

use reqwest::{blocking::Client, Url};
use serde_json::Value;

use crate::{
    constants::DEFAULT_REFRESH_TIMEOUT_SECS,
    error::AuthProfileError,
    models::{
        AuthCredential, AuthProvider, AuthProviderKind, AuthProfileRecord, OAuthRefreshError,
        OAuthRefreshOutcome, OAuthRefreshOutcomeKind, OAuthRefreshRequest, OAuthRefreshResponse,
        OAuthRefreshState, ProviderBackoffPolicy,
    },
    validation::validate_runtime_token_endpoint,
};

pub trait OAuthRefreshAdapter: Send + Sync {
    fn refresh_access_token(
        &self,
        request: &OAuthRefreshRequest,
    ) -> Result<OAuthRefreshResponse, OAuthRefreshError>;
}

#[derive(Debug)]
pub struct HttpOAuthRefreshAdapter {
    timeout: Duration,
}

impl HttpOAuthRefreshAdapter {
    pub fn with_timeout(timeout: Duration) -> Result<Self, AuthProfileError> {
        if timeout.is_zero() {
            return Err(AuthProfileError::InvalidField {
                field: "oauth.timeout",
                message: "timeout must be greater than zero".to_owned(),
            });
        }
        Ok(Self { timeout })
    }
}

impl Default for HttpOAuthRefreshAdapter {
    fn default() -> Self {
        Self::with_timeout(Duration::from_secs(DEFAULT_REFRESH_TIMEOUT_SECS))
            .expect("default oauth refresh adapter should initialize")
    }
}

impl OAuthRefreshAdapter for HttpOAuthRefreshAdapter {
    fn refresh_access_token(
        &self,
        request: &OAuthRefreshRequest,
    ) -> Result<OAuthRefreshResponse, OAuthRefreshError> {
        let token_endpoint = validate_runtime_token_endpoint(request.token_endpoint.as_str())?;
        let client = Client::builder()
            .timeout(self.timeout)
            .redirect(reqwest::redirect::Policy::none())
            .no_proxy()
            .build()
            .map_err(|error| OAuthRefreshError::Transport(error.to_string()))?;
        let mut form_fields = vec![
            ("grant_type".to_owned(), "refresh_token".to_owned()),
            ("refresh_token".to_owned(), request.refresh_token.clone()),
        ];
        if let Some(client_id) = request.client_id.as_deref() {
            form_fields.push(("client_id".to_owned(), client_id.to_owned()));
        }
        if let Some(client_secret) = request.client_secret.as_deref() {
            form_fields.push(("client_secret".to_owned(), client_secret.to_owned()));
        }
        if !request.scopes.is_empty() {
            form_fields.push(("scope".to_owned(), request.scopes.join(" ")));
        }

        let response = client
            .post(token_endpoint)
            .form(&form_fields)
            .send()
            .map_err(|error| OAuthRefreshError::Transport(error.to_string()))?;
        let status = response.status();
        let payload =
            response.text().map_err(|error| OAuthRefreshError::Transport(error.to_string()))?;
        if !status.is_success() {
            return Err(OAuthRefreshError::HttpStatus { status: status.as_u16() });
        }

        let parsed: Value = serde_json::from_str(payload.as_str()).map_err(|error| {
            OAuthRefreshError::InvalidResponse(format!("response body is not JSON: {error}"))
        })?;
        let access_token = parsed
            .get("access_token")
            .and_then(Value::as_str)
            .map(str::trim)
            .filter(|value| !value.is_empty())
            .ok_or_else(|| {
                OAuthRefreshError::InvalidResponse(
                    "response is missing non-empty 'access_token'".to_owned(),
                )
            })?
            .to_owned();
        let refresh_token = parsed
            .get("refresh_token")
            .and_then(Value::as_str)
            .map(str::trim)
            .filter(|value| !value.is_empty())
            .map(ToOwned::to_owned);
        let expires_in_seconds = match parsed.get("expires_in") {
            Some(Value::Number(value)) => value.as_u64(),
            Some(Value::String(value)) => value.parse::<u64>().ok(),
            Some(_) | None => None,
        };

        Ok(OAuthRefreshResponse { access_token, refresh_token, expires_in_seconds })
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OAuthRefreshOutcomeKind {
    SkippedNotOauth,
    SkippedNotDue,
    SkippedCooldown,
    Succeeded,
    Failed,
}

impl OAuthRefreshOutcomeKind {
    #[must_use]
    pub const fn attempted(self) -> bool {
        matches!(self, Self::Succeeded | Self::Failed)
    }

    #[must_use]
    pub const fn success(self) -> bool {
        matches!(self, Self::Succeeded)
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct OAuthRefreshOutcome {
    pub profile_id: String,
    pub provider: String,
    pub kind: OAuthRefreshOutcomeKind,
    pub reason: String,
    pub next_allowed_refresh_unix_ms: Option<i64>,
    pub expires_at_unix_ms: Option<i64>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ProviderBackoffPolicy {
    pub base_backoff_ms: u64,
    pub max_backoff_ms: u64,
}

pub fn provider_backoff_policy(provider: &AuthProvider) -> ProviderBackoffPolicy {
    match provider.kind {
        AuthProviderKind::Openai => {
            ProviderBackoffPolicy { base_backoff_ms: 15_000, max_backoff_ms: 5 * 60 * 1_000 }
        }
        AuthProviderKind::Anthropic => {
            ProviderBackoffPolicy { base_backoff_ms: 20_000, max_backoff_ms: 10 * 60 * 1_000 }
        }
        AuthProviderKind::Telegram
        | AuthProviderKind::Slack
        | AuthProviderKind::Discord
        | AuthProviderKind::Webhook
        | AuthProviderKind::Custom => {
            ProviderBackoffPolicy { base_backoff_ms: 30_000, max_backoff_ms: 30 * 60 * 1_000 }
        }
    }
}

pub fn compute_backoff_ms(provider: &AuthProvider, failure_count: u32) -> u64 {
    let policy = provider_backoff_policy(provider);
    if failure_count == 0 {
        return policy.base_backoff_ms;
    }
    let shift = failure_count.saturating_sub(1).min(20);
    let factor = 1_u64 << shift;
    policy.base_backoff_ms.saturating_mul(factor).min(policy.max_backoff_ms)
}


#[derive(Debug, Clone)]
struct OAuthRefreshSnapshot {
    profile_id: String,
    provider: AuthProvider,
    access_token_vault_ref: String,
    refresh_token_vault_ref: String,
    token_endpoint: String,
    client_id: Option<String>,
    client_secret_vault_ref: Option<String>,
    scopes: Vec<String>,
    expires_at_unix_ms: Option<i64>,
    failure_count: u32,
    observed_updated_at_unix_ms: i64,
}

enum PreparedOAuthRefresh {
    Snapshot(OAuthRefreshSnapshot),
    Outcome(OAuthRefreshOutcome),
}

fn prepare_oauth_refresh_snapshot(
    profile: &AuthProfileRecord,
    now_unix_ms: i64,
) -> PreparedOAuthRefresh {
    let AuthCredential::Oauth {
        access_token_vault_ref,
        refresh_token_vault_ref,
        token_endpoint,
        client_id,
        client_secret_vault_ref,
        scopes,
        expires_at_unix_ms,
        refresh_state,
    } = &profile.credential
    else {
        return PreparedOAuthRefresh::Outcome(OAuthRefreshOutcome {
            profile_id: profile.profile_id.clone(),
            provider: profile.provider.label(),
            kind: OAuthRefreshOutcomeKind::SkippedNotOauth,
            reason: "refresh skipped because profile uses api_key credentials".to_owned(),
            next_allowed_refresh_unix_ms: None,
            expires_at_unix_ms: None,
        });
    };
    if let Some(next_allowed) = refresh_state.next_allowed_refresh_unix_ms {
        if now_unix_ms < next_allowed {
            return PreparedOAuthRefresh::Outcome(OAuthRefreshOutcome {
                profile_id: profile.profile_id.clone(),
                provider: profile.provider.label(),
                kind: OAuthRefreshOutcomeKind::SkippedCooldown,
                reason: "refresh skipped due to cooldown after previous failures".to_owned(),
                next_allowed_refresh_unix_ms: Some(next_allowed),
                expires_at_unix_ms: *expires_at_unix_ms,
            });
        }
    }

    PreparedOAuthRefresh::Snapshot(OAuthRefreshSnapshot {
        profile_id: profile.profile_id.clone(),
        provider: profile.provider.clone(),
        access_token_vault_ref: access_token_vault_ref.clone(),
        refresh_token_vault_ref: refresh_token_vault_ref.clone(),
        token_endpoint: token_endpoint.clone(),
        client_id: client_id.clone(),
        client_secret_vault_ref: client_secret_vault_ref.clone(),
        scopes: scopes.clone(),
        expires_at_unix_ms: *expires_at_unix_ms,
        failure_count: refresh_state.failure_count,
        observed_updated_at_unix_ms: profile.updated_at_unix_ms,
    })
}


